language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
install:
  - pip install setuptools --upgrade
  - python setup.py install
script:
  - flask_s3_viewer -h
notifications:
  email: d.hidekuma@gmail.com
